# Generated by Django 2.2.2 on 2019-07-06 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='isRelatedTo',
            fields=[
                ('question1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='question1', serialize=False, to='polls.Question')),
                ('question2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question2', to='polls.Question')),
                ('question3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question3', to='polls.Question')),
            ],
        ),
    ]
