# Generated by Django 2.2.2 on 2019-08-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190806_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_order',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='isRelatedTo',
        ),
    ]
